version: "3.8"
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      APP_PORT: 8080
      REDIS_HOST: redis
      GIN_MODE: release
    depends_on:
      - redis
  redis:
    image: redis:6